name: realm_walk
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Network
  http: ^1.5.0
  dio: ^5.9.0
  connectivity_plus: ^4.0.2
  vexana: ^5.0.3

  # States
  provider: ^6.1.5+1
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  mobx_codegen: ^2.7.0

  #Media
  audioplayers: ^6.4.0
  file_picker: ^9.2.1
  image_picker: ^1.1.2
  image_cropper: ^9.0.0

  # Animation
  flutter_animate: ^4.5.2
  # flutter_slidable: ^4.0.0
  # #https://www.youtube.com/watch?v=2kQHkBgjAAY&ab_channel=MitchKoko : slidable
  # simple_ripple_animation: ^0.1.0
  # animate_do: ^4.2.0

  # SVG/ICONS
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0

  # Permission
  permission_handler: ^11.4.0

  # Firebase
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.7.10
  firebase_performance: ^0.9.2+5
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  firebase_analytics: ^10.8.0

  #Core
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.6

  #Others
  json_annotation: ^4.9.0
  intl: any
  http_parser: ^4.1.2
  path: ^1.9.1
  cached_network_image: ^3.4.1
  mixpanel_flutter: ^2.3.4
  go_router: ^14.8.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.12
  flutter_timezone: ^4.1.0
  sensors_plus: ^7.0.0
  universal_io: ^2.2.2
  shared_preferences: ^2.5.3
  flutter_webrtc: ^0.14.2
  web_socket_channel: ^3.0.3
  google_mobile_ads: ^6.0.0
  firebase_app_check: ^0.2.2
  firebase_remote_config: ^4.4.7
  flutter_foreground_task: ^8.17.0
  webview_flutter: ^4.13.0
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.2
  camera: ^0.11.2
  # arcore_flutter_plugin: ^0.1.0
  flutter_secure_storage: ^9.2.4
  email_validator: ^3.0.0
  jose: ^0.3.5
  upgrader: ^12.0.0
  in_app_update: ^4.2.5
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15 # flutter pub run build_runner watch
  json_serializable: ^6.9.0
  intl_utils: ^2.8.11

flutter_native_splash:
  # dart run flutter_native_splash:create
  color: "#F22E63"
  image: assets/images/logo.png
  # branding: assets/images/splash.png
  # branding_bottom_padding: 24
  color_dark: "#F22E63"
  image_dark: assets/images/logo.png
  # branding_dark: assets/images/splash.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#F22E63"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#F22E63"
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/audio/ringtone.mp3
    - assets/audio/beep_sound.mp3
    - assets/audio/last_seconds.mp3
    - assets/audio/reconnect.mp3
    - assets/audio/button_click.mp3
    - assets/audio/button_alert.mp3
    - assets/audio/fail.mp3
    - assets/audio/fire.mp3
    - assets/images/
    - assets/icons/svg/
    - assets/illustrations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
        
flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
